/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.rkumar0206.k8gen;

import org.junit.jupiter.api.io.TempDir;

import java.io.File;

class K8GenAiPluginPluginFunctionalTest {
    @TempDir
    File projectDir;

    private File getBuildFile() {
        return new File(projectDir, "build.gradle");
    }

    private File getSettingsFile() {
        return new File(projectDir, "settings.gradle");
    }
}
